language: python

python:
  - "3.5"
  - "3.6"

sudo: false

before_install:
  - pip install -r "requirements.txt"
  - pip install flake8
  - pip install coveralls

install:
  - pip install .

script:
  - flake8 ./cereslib
  - cd tests
  - coverage run --source=cereslib run_tests.py

after_success:
  - coveralls
